In [1386]:
import pandas as pd
import numpy as np
df = pd.read_csv('train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [1387]:
def print_nan_cols(df, moderate_only = False):
    values = list(zip(list(df.isnull().columns), list(df.isnull().any())))
    filtered = list(filter(lambda x: x[1][1] == True, enumerate(values)))
    contains_nan = [y for x, y in filtered]
    proportion_nan = [sum(df[x].isnull()) / len(df[x]) for x, y in contains_nan]
    proportion_nan = [(x[0], proportion_nan[i]) for i, x in enumerate(contains_nan)]
    for col, propo_nan in proportion_nan:
        if abs(propo_nan) > 0.3 or moderate_only is False:
            print(col, ': ', propo_nan)
            
print_nan_cols(df, moderate_only=True)

Alley :  0.9376712328767123
FireplaceQu :  0.4726027397260274
PoolQC :  0.9952054794520548
Fence :  0.8075342465753425
MiscFeature :  0.963013698630137

In [1388]:
df['Alley'].dtype

dtype('O')

In [1389]:
def print_moderate_correlations(df, col_to_correlate):
    cols = df[df.columns].corr().columns
    if df[col_to_correlate].dtype.name == 'category':
        df[col_to_correlate] = df[col_to_correlate].cat.codes
    corrs = df[df.columns].corr()[col_to_correlate]
    for col, corr in zip(cols, corrs):
        if abs(corr) > 0.4 and col != col_to_correlate:
            print(col, ': ', corr)

In [1390]:
df['Alley'] = df['Alley'].astype("category")
df['Alley'] = df['Alley'].cat.add_categories(['None'])
df['Alley'] = df['Alley'].fillna('None')
print_moderate_correlations(df, 'Alley')

OverallQual :  1.0

In [1391]:
df['PoolQC'] = df['PoolQC'].astype("category")
df['PoolQC'] = df['PoolQC'].cat.add_categories(['None'])
df['PoolQC'] = df['PoolQC'].fillna('None')
print_moderate_correlations(df, 'PoolQC')

PoolArea :  -0.8842503024390909
MiscVal :  1.0

In [1392]:
df[df['MiscFeature'] != np.nan].head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,2,Reg,Lvl,AllPub,...,0,3,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,2,Reg,Lvl,AllPub,...,0,3,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,2,IR1,Lvl,AllPub,...,0,3,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,2,IR1,Lvl,AllPub,...,0,3,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,2,IR1,Lvl,AllPub,...,0,3,NaN,NaN,0,12,2008,WD,Normal,250000

In [1393]:
df['MiscFeature'] = df['MiscFeature'].astype("category")
df['MiscFeature'] = df['MiscFeature'].cat.add_categories(['None'])
df['MiscFeature'] = df['MiscFeature'].fillna('None')
print_moderate_correlations(df, 'MiscFeature')

MiscVal :  1.0
MoSold :  -0.5851940568388929

In [1394]:
df['FireplaceQu'] = df['FireplaceQu'].astype("category")
df['FireplaceQu'] = df['FireplaceQu'].cat.add_categories(['None'])
df['FireplaceQu'] = df['FireplaceQu'].fillna('None')
print_moderate_correlations(df, 'FireplaceQu')

OverallQual :  -0.4278363448089896
Fireplaces :  -0.7282891760748185
GarageYrBlt :  1.0

In [1395]:
df['Fence'] = df['Fence'].astype("category")
df['Fence'] = df['Fence'].cat.add_categories(['None'])
df['Fence'] = df['Fence'].fillna('None')
print_moderate_correlations(df, 'Fence')

MiscFeature :  1.0

In [1396]:
# df = df.drop(columns=['Alley', 'Fence'])
# df = df * 1

In [1397]:
print_nan_cols(df)

LotFrontage :  0.1773972602739726
MasVnrType :  0.005479452054794521
MasVnrArea :  0.005479452054794521
BsmtQual :  0.025342465753424658
BsmtCond :  0.025342465753424658
BsmtExposure :  0.026027397260273973
BsmtFinType1 :  0.025342465753424658
BsmtFinType2 :  0.026027397260273973
Electrical :  0.0006849315068493151
GarageType :  0.05547945205479452
GarageYrBlt :  0.05547945205479452
GarageFinish :  0.05547945205479452
GarageQual :  0.05547945205479452
GarageCond :  0.05547945205479452

In [1398]:
print_moderate_correlations(df, 'LotFrontage')

LotArea :  0.4260950187718087
1stFlrSF :  0.4571810019946558
GrLivArea :  0.40279741408532066

In [1399]:
df['LotFrontage'].head(10)

0    65.0
1    80.0
2    68.0
3    60.0
4    84.0
5    85.0
6    75.0
7     NaN
8    51.0
9    50.0
Name: LotFrontage, dtype: float64

In [1400]:
values = list(zip(list(df.isnull().columns), list(df.isnull().any())))
filtered = list(filter(lambda x: x[1][1] == True, enumerate(values)))
contains_nan = [y for x, y in filtered]
contains_nan

[('LotFrontage', True),
 ('MasVnrType', True),
 ('MasVnrArea', True),
 ('BsmtQual', True),
 ('BsmtCond', True),
 ('BsmtExposure', True),
 ('BsmtFinType1', True),
 ('BsmtFinType2', True),
 ('Electrical', True),
 ('GarageType', True),
 ('GarageYrBlt', True),
 ('GarageFinish', True),
 ('GarageQual', True),
 ('GarageCond', True)]

In [1401]:
predict_missing_df = df

for column, value  in contains_nan:
    predict_missing_df = predict_missing_df.drop(columns=[column])

In [1402]:
def convert_categorical_to_numbers(to_change_df, numbers=True):
    for col, dtype in zip(to_change_df.columns, to_change_df.dtypes):
        if (dtype == object):
            to_change_df[col] = to_change_df[col].astype('category')
    if numbers:
        return pd.get_dummies(to_change_df)
    else:
        return to_change_df

In [1403]:
predict_missing_df = convert_categorical_to_numbers(predict_missing_df)

In [1404]:
predict_missing_df.head()

,Id,MSSubClass,LotArea,Alley,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,8450,2,7,5,2003,2003,706,0,...,0,0,0,1,0,0,0,0,1,0
1,2,20,9600,2,6,8,1976,1976,978,0,...,0,0,0,1,0,0,0,0,1,0
2,3,60,11250,2,7,5,2001,2002,486,0,...,0,0,0,1,0,0,0,0,1,0
3,4,70,9550,2,7,5,1915,1970,216,0,...,0,0,0,1,1,0,0,0,0,0
4,5,60,14260,2,8,5,2000,2000,655,0,...,0,0,0,1,0,0,0,0,1,0

In [1405]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

def replace_missing_with_ml(df, predict_missing_df, col_to_predict, is_classify=False):

    predict_missing_df[col_to_predict] = df[col_to_predict]
    adjusted_missing = predict_missing_df[predict_missing_df[col_to_predict].isnull() == False]

    y = adjusted_missing[col_to_predict].values
    x = adjusted_missing.drop(columns=[col_to_predict]).values

    x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)
    
    if is_classify:
        rf = RandomForestClassifier(n_estimators=300, min_samples_leaf=5, random_state=42)
    else:
        rf = RandomForestRegressor(n_estimators=300, min_samples_leaf=5, random_state=42)
        
    rf.fit(x_train, y_train)
    r2 = r2_score(y_test, rf.predict(x_test))
    mse = mean_squared_error(y_test, rf.predict(x_test))
    rmse = mse**(1/2)
    print('R2          : ', round(r2, 4))
    print('RMSE        : ', round(rmse, 2))

    missing_df = predict_missing_df[predict_missing_df[col_to_predict].isnull()]
    x_missing = missing_df.drop(columns=[col_to_predict]).values
    predictions = rf.predict(x_missing).astype(int)

    df.loc[df[col_to_predict].isnull(), col_to_predict] = predictions
    
    predict_missing_df = predict_missing_df.drop(columns=[col_to_predict])
    return df, predict_missing_df

In [1406]:
print_nan_cols(df)

LotFrontage :  0.1773972602739726
MasVnrType :  0.005479452054794521
MasVnrArea :  0.005479452054794521
BsmtQual :  0.025342465753424658
BsmtCond :  0.025342465753424658
BsmtExposure :  0.026027397260273973
BsmtFinType1 :  0.025342465753424658
BsmtFinType2 :  0.026027397260273973
Electrical :  0.0006849315068493151
GarageType :  0.05547945205479452
GarageYrBlt :  0.05547945205479452
GarageFinish :  0.05547945205479452
GarageQual :  0.05547945205479452
GarageCond :  0.05547945205479452

In [1407]:
df, _ = replace_missing_with_ml(df, predict_missing_df, 'LotFrontage')

R2          :  0.5995
RMSE        :  14.33

In [1408]:
df['MasVnrType'].head()

0    BrkFace
1       None
2    BrkFace
3       None
4    BrkFace
Name: MasVnrType, dtype: object

In [1409]:
df['MasVnrType'] = df['MasVnrType'].fillna('None')
df['MasVnrArea'] = df['MasVnrArea'].fillna(0)

In [1410]:
df['BsmtQual'].head()

0    Gd
1    Gd
2    Gd
3    TA
4    Gd
Name: BsmtQual, dtype: object

In [1411]:
df['BsmtQual'] = df['BsmtQual'].fillna('None')
df['BsmtCond'] = df['BsmtCond'].fillna('None')
df['BsmtExposure'] = df['BsmtExposure'].fillna('None')
df['BsmtFinType1'] = df['BsmtFinType1'].fillna('None')
df['BsmtFinType2'] = df['BsmtFinType2'].fillna('None')

In [1412]:
df['Electrical'].head()

0    SBrkr
1    SBrkr
2    SBrkr
3    SBrkr
4    SBrkr
Name: Electrical, dtype: object

In [1413]:
df['Electrical'] = df['Electrical'].fillna('None')

In [1414]:
df['MasVnrArea'].head()

0    196.0
1      0.0
2    162.0
3      0.0
4    350.0
Name: MasVnrArea, dtype: float64

In [1415]:
df['GarageYrBlt'].head()

0    2003.0
1    1976.0
2    2001.0
3    1998.0
4    2000.0
Name: GarageYrBlt, dtype: float64

In [1416]:
print_nan_cols(df)

GarageType :  0.05547945205479452
GarageYrBlt :  0.05547945205479452
GarageFinish :  0.05547945205479452
GarageQual :  0.05547945205479452
GarageCond :  0.05547945205479452

In [1417]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley               int8
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
                  ...
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu         int8
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC              int8
Fence               int8
MiscFeature         int8
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [1418]:
df['GarageType'] = df['GarageType'].fillna('None')
df['GarageYrBlt'] = df['GarageYrBlt'].fillna(0)
df['GarageFinish'] = df['GarageFinish'].fillna('None')
df['GarageQual'] = df['GarageQual'].fillna('None')
df['GarageCond'] = df['GarageCond'].fillna('None')

In [1419]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,2,Reg,Lvl,AllPub,...,0,3,4,4,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,2,Reg,Lvl,AllPub,...,0,3,4,4,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,2,IR1,Lvl,AllPub,...,0,3,4,4,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,2,IR1,Lvl,AllPub,...,0,3,4,4,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,2,IR1,Lvl,AllPub,...,0,3,4,4,0,12,2008,WD,Normal,250000

In [1420]:
df = convert_categorical_to_numbers(df, numbers=False)

In [1421]:
df.dtypes

Id                  int64
MSSubClass          int64
MSZoning         category
LotFrontage       float64
LotArea             int64
Street           category
Alley                int8
LotShape         category
LandContour      category
Utilities        category
LotConfig        category
LandSlope        category
Neighborhood     category
Condition1       category
Condition2       category
BldgType         category
HouseStyle       category
OverallQual         int64
OverallCond         int64
YearBuilt           int64
YearRemodAdd        int64
RoofStyle        category
RoofMatl         category
Exterior1st      category
Exterior2nd      category
MasVnrType       category
MasVnrArea        float64
ExterQual        category
ExterCond        category
Foundation       category
                   ...
BedroomAbvGr        int64
KitchenAbvGr        int64
KitchenQual      category
TotRmsAbvGrd        int64
Functional       category
Fireplaces          int64
FireplaceQu          int8
GarageType       category
GarageYrBlt       float64
GarageFinish     category
GarageCars          int64
GarageArea          int64
GarageQual       category
GarageCond       category
PavedDrive       category
WoodDeckSF          int64
OpenPorchSF         int64
EnclosedPorch       int64
3SsnPorch           int64
ScreenPorch         int64
PoolArea            int64
PoolQC               int8
Fence                int8
MiscFeature          int8
MiscVal             int64
MoSold              int64
YrSold              int64
SaleType         category
SaleCondition    category
SalePrice           int64
Length: 81, dtype: object

In [1422]:
for col, dtype in zip(df.columns, df.dtypes):
    if dtype == 'int64':
        print(col)

Id
MSSubClass
LotArea
OverallQual
OverallCond
YearBuilt
YearRemodAdd
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
TotRmsAbvGrd
Fireplaces
GarageCars
GarageArea
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
MiscVal
MoSold
YrSold
SalePrice

In [1423]:
df = df.drop(columns=['Id'])

In [1424]:
# df['YearBuilt'] = df['YearBuilt'].astype('category')
df['PoolQC'] = df['PoolQC'].astype('category')
df['MiscFeature'] = df['MiscFeature'].astype('category')
df['FireplaceQu'] = df['FireplaceQu'].astype('category')
# df['YearRemodAdd'] = df['YearRemodAdd'].astype('category')
df['MoSold'] = df['MoSold'].astype('category')
# df['YrSold'] = df['YrSold'].astype('category')

In [1425]:
df_test = pd.read_csv("test.csv")
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [1426]:
for col, dtype in zip(df.columns, df.dtypes):
    if dtype.name == 'category':
        print(col)
        df_test[col] = df[col].astype('category')
        df_test[col].cat.categories = df[col].cat.categories

MSZoning
Street
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
MasVnrType
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinType2
Heating
HeatingQC
CentralAir
Electrical
KitchenQual
Functional
FireplaceQu
GarageType
GarageFinish
GarageQual
GarageCond
PavedDrive
PoolQC
MiscFeature
MoSold
SaleType
SaleCondition

In [1427]:
df_test.dtypes

Id                  int64
MSSubClass          int64
MSZoning         category
LotFrontage       float64
LotArea             int64
Street           category
Alley              object
LotShape         category
LandContour      category
Utilities        category
LotConfig        category
LandSlope        category
Neighborhood     category
Condition1       category
Condition2       category
BldgType         category
HouseStyle       category
OverallQual         int64
OverallCond         int64
YearBuilt           int64
YearRemodAdd        int64
RoofStyle        category
RoofMatl         category
Exterior1st      category
Exterior2nd      category
MasVnrType       category
MasVnrArea        float64
ExterQual        category
ExterCond        category
Foundation       category
                   ...
HalfBath            int64
BedroomAbvGr        int64
KitchenAbvGr        int64
KitchenQual      category
TotRmsAbvGrd        int64
Functional       category
Fireplaces          int64
FireplaceQu      category
GarageType       category
GarageYrBlt       float64
GarageFinish     category
GarageCars        float64
GarageArea        float64
GarageQual       category
GarageCond       category
PavedDrive       category
WoodDeckSF          int64
OpenPorchSF         int64
EnclosedPorch       int64
3SsnPorch           int64
ScreenPorch         int64
PoolArea            int64
PoolQC           category
Fence              object
MiscFeature      category
MiscVal             int64
MoSold           category
YrSold              int64
SaleType         category
SaleCondition    category
Length: 80, dtype: object

In [1435]:
print_nan_cols(df_test)

LotFrontage :  0.15558601782042494
Alley :  0.9266620973269363
MasVnrArea :  0.01028101439342015
BsmtFinSF1 :  0.0006854009595613434
BsmtFinSF2 :  0.0006854009595613434
BsmtUnfSF :  0.0006854009595613434
TotalBsmtSF :  0.0006854009595613434
BsmtFullBath :  0.0013708019191226869
BsmtHalfBath :  0.0013708019191226869
GarageYrBlt :  0.053461274845784786
GarageCars :  0.0006854009595613434
GarageArea :  0.0006854009595613434
Fence :  0.8012337217272104

In [ ]:
values = list(zip(list(df_test.isnull().columns), list(df_test.isnull().any())))
filtered = list(filter(lambda x: x[1][1] == True, enumerate(values)))
contains_nan = [y for x, y in filtered]
contains_nan

In [ ]:
predict_missing_df_test = df_test

for column, value  in contains_nan:
    predict_missing_df_test = predict_missing_df_test.drop(columns=[column])

In [ ]:
predict_missing_df_test = convert_categorical_to_numbers(predict_missing_df_test)

In [ ]:
df_test, _ = replace_missing_with_ml(df_test, predict_missing_df_test, 'LotFrontage')

In [1428]:
df = convert_categorical_to_numbers(df)

df.to_csv("clean_data.csv")

In [1429]:
df.head()

,MSSubClass,LotFrontage,LotArea,Alley,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,2,7,5,2003,2003,196.0,706,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,2,6,8,1976,1976,0.0,978,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,2,7,5,2001,2002,162.0,486,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,2,7,5,1915,1970,0.0,216,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,2,8,5,2000,2000,350.0,655,...,0,0,0,1,0,0,0,0,1,0

In [1430]:
df.corr()['SalePrice']

MSSubClass              -0.084284
LotFrontage              0.351651
LotArea                  0.263843
Alley                    0.139868
OverallQual              0.790982
OverallCond             -0.077856
YearBuilt                0.522897
YearRemodAdd             0.507101
MasVnrArea               0.472614
BsmtFinSF1               0.386420
BsmtFinSF2              -0.011378
BsmtUnfSF                0.214479
TotalBsmtSF              0.613581
1stFlrSF                 0.605852
2ndFlrSF                 0.319334
LowQualFinSF            -0.025606
GrLivArea                0.708624
BsmtFullBath             0.227122
BsmtHalfBath            -0.016844
FullBath                 0.560664
HalfBath                 0.284108
BedroomAbvGr             0.168213
KitchenAbvGr            -0.135907
TotRmsAbvGrd             0.533723
Fireplaces               0.466929
GarageYrBlt              0.261366
GarageCars               0.640409
GarageArea               0.623431
WoodDeckSF               0.324413
OpenPorchSF              0.315856
                           ...
MiscFeature_2           -0.069771
MiscFeature_3            0.022773
MiscFeature_4            0.072298
MoSold_1                 0.005980
MoSold_2                -0.007355
MoSold_3                 0.008219
MoSold_4                -0.038774
MoSold_5                -0.043714
MoSold_6                -0.020324
MoSold_7                 0.029762
MoSold_8                 0.014185
MoSold_9                 0.039474
MoSold_10               -0.004354
MoSold_11                0.034001
MoSold_12                0.014465
SaleType_COD            -0.081047
SaleType_CWD             0.019588
SaleType_Con             0.041357
SaleType_ConLD          -0.041791
SaleType_ConLI           0.014371
SaleType_ConLw          -0.027475
SaleType_New             0.357509
SaleType_Oth            -0.034895
SaleType_WD             -0.242598
SaleCondition_Abnorml   -0.118069
SaleCondition_AdjLand   -0.050686
SaleCondition_Alloca    -0.015525
SaleCondition_Family    -0.046480
SaleCondition_Normal    -0.153990
SaleCondition_Partial    0.352060
Name: SalePrice, Length: 309, dtype: float64

In [1431]:
def get_moderate_corrs(df, col_to_correlate):
    cols = df[df.columns].corr().columns
    corrs = df[df.columns].corr()[col_to_correlate]
    for col, corr in zip(cols, corrs):
        if abs(corr) < 0.05 and col != col_to_correlate:
            df = df.drop(columns=[col])
    return df

In [1432]:
df = get_moderate_corrs(df, 'SalePrice')

In [1433]:
df.head()

,MSSubClass,LotFrontage,LotArea,Alley,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,PoolQC_3,MiscFeature_2,MiscFeature_4,SaleType_COD,SaleType_New,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,2,7,5,2003,2003,196.0,706,...,1,0,1,0,0,1,0,0,1,0
1,20,80.0,9600,2,6,8,1976,1976,0.0,978,...,1,0,1,0,0,1,0,0,1,0
2,60,68.0,11250,2,7,5,2001,2002,162.0,486,...,1,0,1,0,0,1,0,0,1,0
3,70,60.0,9550,2,7,5,1915,1970,0.0,216,...,1,0,1,0,0,1,1,0,0,0
4,60,84.0,14260,2,8,5,2000,2000,350.0,655,...,1,0,1,0,0,1,0,0,1,0

In [1434]:
df.to_csv("clean_data.csv")