In [936]:
import pandas as pd
import numpy as np
df = pd.read_csv('train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [937]:
def print_nan_cols(df, moderate_only = False):
    values = list(zip(list(df.isnull().columns), list(df.isnull().any())))
    filtered = list(filter(lambda x: x[1][1] == True, enumerate(values)))
    contains_nan = [y for x, y in filtered]
    proportion_nan = [sum(df[x].isnull()) / len(df[x]) for x, y in contains_nan]
    proportion_nan = [(x[0], proportion_nan[i]) for i, x in enumerate(contains_nan)]
    for col, propo_nan in proportion_nan:
        if abs(propo_nan) > 0.3 or moderate_only is False:
            print(col, ': ', propo_nan)
            
print_nan_cols(df, moderate_only=True)

Alley :  0.9376712328767123
FireplaceQu :  0.4726027397260274
PoolQC :  0.9952054794520548
Fence :  0.8075342465753425
MiscFeature :  0.963013698630137

In [938]:
df['Alley'].dtype

dtype('O')

In [939]:
def print_moderate_correlations(df, col_to_correlate):
    cols = df[df.columns].corr().columns
    if df[col_to_correlate].dtype.name == 'category':
        df[col_to_correlate] = df[col_to_correlate].cat.codes
    corrs = df[df.columns].corr()[col_to_correlate]
    for col, corr in zip(cols, corrs):
        if abs(corr) > 0.4 and col != col_to_correlate:
            print(col, ': ', corr)

In [940]:
df['Alley'] = df['Alley'].astype("category")
df['Alley'] = df['Alley'].cat.add_categories(['None'])
df['Alley'] = df['Alley'].fillna('None')
print_moderate_correlations(df, 'Alley')

OverallQual :  1.0

In [941]:
df['PoolQC'] = df['PoolQC'].astype("category")
df['PoolQC'] = df['PoolQC'].cat.add_categories(['None'])
df['PoolQC'] = df['PoolQC'].fillna('None')
print_moderate_correlations(df, 'PoolQC')

PoolArea :  -0.8842503024390909
MiscVal :  1.0

In [942]:
df[df['MiscFeature'] != np.nan].head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,2,Reg,Lvl,AllPub,...,0,3,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,2,Reg,Lvl,AllPub,...,0,3,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,2,IR1,Lvl,AllPub,...,0,3,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,2,IR1,Lvl,AllPub,...,0,3,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,2,IR1,Lvl,AllPub,...,0,3,NaN,NaN,0,12,2008,WD,Normal,250000

In [943]:
df['MiscFeature'] = df['MiscFeature'].astype("category")
df['MiscFeature'] = df['MiscFeature'].cat.add_categories(['None'])
df['MiscFeature'] = df['MiscFeature'].fillna('None')
print_moderate_correlations(df, 'MiscFeature')

MiscVal :  1.0
MoSold :  -0.5851940568388929

In [944]:
df['FireplaceQu'] = df['FireplaceQu'].astype("category")
df['FireplaceQu'] = df['FireplaceQu'].cat.add_categories(['None'])
df['FireplaceQu'] = df['FireplaceQu'].fillna('None')
print_moderate_correlations(df, 'FireplaceQu')

OverallQual :  -0.4278363448089896
Fireplaces :  -0.7282891760748185
GarageYrBlt :  1.0

In [945]:
df['Fence'] = df['Fence'].astype("category")
df['Fence'] = df['Fence'].cat.add_categories(['None'])
df['Fence'] = df['Fence'].fillna('None')
print_moderate_correlations(df, 'Fence')

MiscFeature :  1.0

In [946]:
# df = df.drop(columns=['Alley', 'Fence'])
# df = df * 1

In [947]:
print_nan_cols(df)

LotFrontage :  0.1773972602739726
MasVnrType :  0.005479452054794521
MasVnrArea :  0.005479452054794521
BsmtQual :  0.025342465753424658
BsmtCond :  0.025342465753424658
BsmtExposure :  0.026027397260273973
BsmtFinType1 :  0.025342465753424658
BsmtFinType2 :  0.026027397260273973
Electrical :  0.0006849315068493151
GarageType :  0.05547945205479452
GarageYrBlt :  0.05547945205479452
GarageFinish :  0.05547945205479452
GarageQual :  0.05547945205479452
GarageCond :  0.05547945205479452

In [948]:
print_moderate_correlations(df, 'LotFrontage')

LotArea :  0.4260950187718087
1stFlrSF :  0.4571810019946558
GrLivArea :  0.40279741408532066

In [949]:
df['LotFrontage'].head(10)

0    65.0
1    80.0
2    68.0
3    60.0
4    84.0
5    85.0
6    75.0
7     NaN
8    51.0
9    50.0
Name: LotFrontage, dtype: float64

In [950]:
values = list(zip(list(df.isnull().columns), list(df.isnull().any())))
filtered = list(filter(lambda x: x[1][1] == True, enumerate(values)))
contains_nan = [y for x, y in filtered]
contains_nan

[('LotFrontage', True),
 ('MasVnrType', True),
 ('MasVnrArea', True),
 ('BsmtQual', True),
 ('BsmtCond', True),
 ('BsmtExposure', True),
 ('BsmtFinType1', True),
 ('BsmtFinType2', True),
 ('Electrical', True),
 ('GarageType', True),
 ('GarageYrBlt', True),
 ('GarageFinish', True),
 ('GarageQual', True),
 ('GarageCond', True)]

In [951]:
predict_missing_df = df

for column, value  in contains_nan:
    predict_missing_df = predict_missing_df.drop(columns=[column])

In [952]:
def convert_categorical_to_numbers(to_change_df, numbers=True):
    for col, dtype in zip(to_change_df.columns, to_change_df.dtypes):
        if (dtype == object):
            to_change_df[col] = to_change_df[col].astype('category').cat.codes
    if numbers:
        return pd.get_dummies(to_change_df)
    else:
        return to_change_df

In [953]:
predict_missing_df = convert_categorical_to_numbers(predict_missing_df)

In [954]:
predict_missing_df.head()

,Id,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,8450,1,2,3,3,0,4,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,9600,1,2,3,3,0,2,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,11250,1,2,0,3,0,4,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,9550,1,2,0,3,0,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,14260,1,2,0,3,0,2,...,0,3,4,4,0,12,2008,8,4,250000

In [955]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

def replace_missing_with_ml(df, predict_missing_df, col_to_predict, is_classify=False):

    predict_missing_df[col_to_predict] = df[col_to_predict]
    adjusted_missing = predict_missing_df[predict_missing_df[col_to_predict].isnull() == False]

    y = adjusted_missing[col_to_predict].values
    x = adjusted_missing.drop(columns=[col_to_predict]).values

    x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)
    
    if is_classify:
        rf = RandomForestClassifier(n_estimators=300, min_samples_leaf=5, random_state=42)
    else:
        rf = RandomForestRegressor(n_estimators=300, min_samples_leaf=5, random_state=42)
        
    rf.fit(x_train, y_train)
    r2 = r2_score(y_test, rf.predict(x_test))
    mse = mean_squared_error(y_test, rf.predict(x_test))
    rmse = mse**(1/2)
    print('R2          : ', round(r2, 4))
    print('RMSE        : ', round(rmse, 2))

    missing_df = predict_missing_df[predict_missing_df[col_to_predict].isnull()]
    x_missing = missing_df.drop(columns=[col_to_predict]).values
    predictions = rf.predict(x_missing).astype(int)

    df.loc[df[col_to_predict].isnull(), col_to_predict] = predictions
    
    predict_missing_df = predict_missing_df.drop(columns=[col_to_predict])
    return df, predict_missing_df

In [956]:
print_nan_cols(df)

LotFrontage :  0.1773972602739726
MasVnrType :  0.005479452054794521
MasVnrArea :  0.005479452054794521
BsmtQual :  0.025342465753424658
BsmtCond :  0.025342465753424658
BsmtExposure :  0.026027397260273973
BsmtFinType1 :  0.025342465753424658
BsmtFinType2 :  0.026027397260273973
Electrical :  0.0006849315068493151
GarageType :  0.05547945205479452
GarageYrBlt :  0.05547945205479452
GarageFinish :  0.05547945205479452
GarageQual :  0.05547945205479452
GarageCond :  0.05547945205479452

In [957]:
df, _ = replace_missing_with_ml(df, predict_missing_df, 'LotFrontage')

R2          :  0.6091
RMSE        :  14.15

In [958]:
df['MasVnrType'].head()

0    BrkFace
1       None
2    BrkFace
3       None
4    BrkFace
Name: MasVnrType, dtype: object

In [959]:
df['MasVnrType'] = df['MasVnrType'].fillna('None')
df['MasVnrArea'] = df['MasVnrArea'].fillna(0)

In [960]:
df['BsmtQual'].head()

0    Gd
1    Gd
2    Gd
3    TA
4    Gd
Name: BsmtQual, dtype: object

In [961]:
df['BsmtQual'] = df['BsmtQual'].fillna('None')
df['BsmtCond'] = df['BsmtCond'].fillna('None')
df['BsmtExposure'] = df['BsmtExposure'].fillna('None')
df['BsmtFinType1'] = df['BsmtFinType1'].fillna('None')
df['BsmtFinType2'] = df['BsmtFinType2'].fillna('None')

In [962]:
df['Electrical'].head()

0    SBrkr
1    SBrkr
2    SBrkr
3    SBrkr
4    SBrkr
Name: Electrical, dtype: object

In [963]:
df['Electrical'] = df['Electrical'].fillna('None')

In [964]:
df['MasVnrArea'].head()

0    196.0
1      0.0
2    162.0
3      0.0
4    350.0
Name: MasVnrArea, dtype: float64

In [965]:
df['GarageYrBlt'].head()

0    2003.0
1    1976.0
2    2001.0
3    1998.0
4    2000.0
Name: GarageYrBlt, dtype: float64

In [966]:
print_nan_cols(df)

GarageType :  0.05547945205479452
GarageYrBlt :  0.05547945205479452
GarageFinish :  0.05547945205479452
GarageQual :  0.05547945205479452
GarageCond :  0.05547945205479452

In [967]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley               int8
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
                  ...
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu         int8
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC              int8
Fence               int8
MiscFeature         int8
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [968]:
df['GarageType'] = df['GarageType'].fillna('None')
df['GarageYrBlt'] = df['GarageYrBlt'].fillna(0)
df['GarageFinish'] = df['GarageFinish'].fillna('None')
df['GarageQual'] = df['GarageQual'].fillna('None')
df['GarageCond'] = df['GarageCond'].fillna('None')

In [969]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,2,Reg,Lvl,AllPub,...,0,3,4,4,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,2,Reg,Lvl,AllPub,...,0,3,4,4,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,2,IR1,Lvl,AllPub,...,0,3,4,4,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,2,IR1,Lvl,AllPub,...,0,3,4,4,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,2,IR1,Lvl,AllPub,...,0,3,4,4,0,12,2008,WD,Normal,250000

In [970]:
df = convert_categorical_to_numbers(df, numbers=False)

In [971]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning            int8
LotFrontage      float64
LotArea            int64
Street              int8
Alley               int8
LotShape            int8
LandContour         int8
Utilities           int8
LotConfig           int8
LandSlope           int8
Neighborhood        int8
Condition1          int8
Condition2          int8
BldgType            int8
HouseStyle          int8
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle           int8
RoofMatl            int8
Exterior1st         int8
Exterior2nd         int8
MasVnrType          int8
MasVnrArea       float64
ExterQual           int8
ExterCond           int8
Foundation          int8
                  ...
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual         int8
TotRmsAbvGrd       int64
Functional          int8
Fireplaces         int64
FireplaceQu         int8
GarageType          int8
GarageYrBlt      float64
GarageFinish        int8
GarageCars         int64
GarageArea         int64
GarageQual          int8
GarageCond          int8
PavedDrive          int8
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC              int8
Fence               int8
MiscFeature         int8
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType            int8
SaleCondition       int8
SalePrice          int64
Length: 81, dtype: object

In [972]:
for col, dtype in zip(df.columns, df.dtypes):
    if dtype == 'int64':
        print(col)

Id
MSSubClass
LotArea
OverallQual
OverallCond
YearBuilt
YearRemodAdd
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
TotRmsAbvGrd
Fireplaces
GarageCars
GarageArea
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
MiscVal
MoSold
YrSold
SalePrice

In [973]:
# df = df.drop(columns=['Id'])

In [974]:
# df['YearBuilt'] = df['YearBuilt'].astype('category')
df['PoolQC'] = df['PoolQC'].astype('category')
df['MiscFeature'] = df['MiscFeature'].astype('category')
df['FireplaceQu'] = df['FireplaceQu'].astype('category')
# df['YearRemodAdd'] = df['YearRemodAdd'].astype('category')
df['MoSold'] = df['MoSold'].astype('category')
# df['YrSold'] = df['YrSold'].astype('category')

In [975]:
df_test = pd.read_csv("test.csv")
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [976]:
for col, dtype in zip(df.columns, df.dtypes):
    if dtype.name == 'category':
        print(col)
        df_test[col] = df[col].astype('category')
        df_test[col].cat.categories = df[col].cat.categories

FireplaceQu
PoolQC
MiscFeature
MoSold

In [977]:
df_test.dtypes

Id                  int64
MSSubClass          int64
MSZoning           object
LotFrontage       float64
LotArea             int64
Street             object
Alley              object
LotShape           object
LandContour        object
Utilities          object
LotConfig          object
LandSlope          object
Neighborhood       object
Condition1         object
Condition2         object
BldgType           object
HouseStyle         object
OverallQual         int64
OverallCond         int64
YearBuilt           int64
YearRemodAdd        int64
RoofStyle          object
RoofMatl           object
Exterior1st        object
Exterior2nd        object
MasVnrType         object
MasVnrArea        float64
ExterQual          object
ExterCond          object
Foundation         object
                   ...
HalfBath            int64
BedroomAbvGr        int64
KitchenAbvGr        int64
KitchenQual        object
TotRmsAbvGrd        int64
Functional         object
Fireplaces          int64
FireplaceQu      category
GarageType         object
GarageYrBlt       float64
GarageFinish       object
GarageCars        float64
GarageArea        float64
GarageQual         object
GarageCond         object
PavedDrive         object
WoodDeckSF          int64
OpenPorchSF         int64
EnclosedPorch       int64
3SsnPorch           int64
ScreenPorch         int64
PoolArea            int64
PoolQC           category
Fence              object
MiscFeature      category
MiscVal             int64
MoSold           category
YrSold              int64
SaleType           object
SaleCondition      object
Length: 80, dtype: object

In [978]:
print_nan_cols(df_test)

MSZoning :  0.0027416038382453737
LotFrontage :  0.15558601782042494
Alley :  0.9266620973269363
Utilities :  0.0013708019191226869
Exterior1st :  0.0006854009595613434
Exterior2nd :  0.0006854009595613434
MasVnrType :  0.010966415352981495
MasVnrArea :  0.01028101439342015
BsmtQual :  0.03015764222069911
BsmtCond :  0.030843043180260453
BsmtExposure :  0.03015764222069911
BsmtFinType1 :  0.02878684030157642
BsmtFinSF1 :  0.0006854009595613434
BsmtFinType2 :  0.02878684030157642
BsmtFinSF2 :  0.0006854009595613434
BsmtUnfSF :  0.0006854009595613434
TotalBsmtSF :  0.0006854009595613434
BsmtFullBath :  0.0013708019191226869
BsmtHalfBath :  0.0013708019191226869
KitchenQual :  0.0006854009595613434
Functional :  0.0013708019191226869
GarageType :  0.0520904729266621
GarageYrBlt :  0.053461274845784786
GarageFinish :  0.053461274845784786
GarageCars :  0.0006854009595613434
GarageArea :  0.0006854009595613434
GarageQual :  0.053461274845784786
GarageCond :  0.053461274845784786
Fence :  0.8012337217272104
SaleType :  0.0006854009595613434

In [979]:
values = list(zip(list(df_test.isnull().columns), list(df_test.isnull().any())))
filtered = list(filter(lambda x: x[1][1] == True, enumerate(values)))
contains_nan = [y for x, y in filtered]

In [980]:
df_test['BsmtFinSF1'] = df_test['BsmtFinSF1'].fillna(0)
df_test['BsmtFinSF2'] = df_test['BsmtFinSF2'].fillna(0)
df_test['BsmtUnfSF'] = df_test['BsmtUnfSF'].fillna(0)
df_test['TotalBsmtSF'] = df_test['TotalBsmtSF'].fillna(0)
df_test['BsmtFullBath'] = df_test['BsmtFullBath'].fillna(0)
df_test['BsmtHalfBath'] = df_test['BsmtHalfBath'].fillna(0)

In [981]:
df_test['GarageYrBlt'] = df_test['GarageYrBlt'].fillna(df_test['GarageYrBlt'].mode()[0])
df_test['GarageCars'] = df_test['GarageCars'].fillna(df_test['GarageCars'].mode()[0])
df_test['GarageArea'] = df_test['GarageArea'].fillna(df_test['GarageArea'].median())

In [982]:
predict_missing_df_test = df_test

for column, value  in contains_nan:
    predict_missing_df_test = predict_missing_df_test.drop(columns=[column])

In [983]:
predict_missing_df_test = convert_categorical_to_numbers(predict_missing_df_test)

In [984]:
df_test, _ = replace_missing_with_ml(df_test, predict_missing_df_test, 'LotFrontage')

R2          :  0.6117
RMSE        :  14.01

In [985]:
# df_test, _ = replace_missing_with_ml(df_test, predict_missing_df_test, 'LotFrontage')

In [986]:
df_test['Alley'] = df_test['Alley'].astype("category")
df_test['Alley'] = df_test['Alley'].cat.add_categories(['None'])
df_test['Alley'] = df_test['Alley'].fillna('None')
print_moderate_correlations(df_test, 'Alley')

OverallQual :  1.0

In [987]:
df_test['Fence'] = df_test['Fence'].astype("category")
df_test['Fence'] = df_test['Fence'].cat.add_categories(['None'])
df_test['Fence'] = df_test['Fence'].fillna('None')
print_moderate_correlations(df_test, 'Fence')

MiscVal :  1.0

In [988]:
df_test['MasVnrArea'] = df_test['MasVnrArea'].fillna(0)

In [989]:
print_nan_cols(df_test)

MSZoning :  0.0027416038382453737
Utilities :  0.0013708019191226869
Exterior1st :  0.0006854009595613434
Exterior2nd :  0.0006854009595613434
MasVnrType :  0.010966415352981495
BsmtQual :  0.03015764222069911
BsmtCond :  0.030843043180260453
BsmtExposure :  0.03015764222069911
BsmtFinType1 :  0.02878684030157642
BsmtFinType2 :  0.02878684030157642
KitchenQual :  0.0006854009595613434
Functional :  0.0013708019191226869
GarageType :  0.0520904729266621
GarageFinish :  0.053461274845784786
GarageQual :  0.053461274845784786
GarageCond :  0.053461274845784786
SaleType :  0.0006854009595613434

In [990]:
print(len(convert_categorical_to_numbers(df_test)))
print(len(convert_categorical_to_numbers(df))) # has y value so +1

1459
1460

In [991]:
df_test = convert_categorical_to_numbers(df_test, numbers=True)
df_test.to_csv("clean_test.csv")

In [992]:
df = convert_categorical_to_numbers(df, numbers=True)

df.to_csv("clean_data.csv")

In [993]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MoSold_3,MoSold_4,MoSold_5,MoSold_6,MoSold_7,MoSold_8,MoSold_9,MoSold_10,MoSold_11,MoSold_12
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,0,0,0,0,0,0,0,0,0
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,0,1,0,0,0,0,0,0,0
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,0,0,0,0,0,1,0,0,0
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,0,0,0,0,0,0,0,0,0
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,0,0,0,0,0,0,0,0,1

In [994]:
df.corr()['SalePrice']

Id              -0.021917
MSSubClass      -0.084284
MSZoning        -0.166872
LotFrontage      0.353632
LotArea          0.263843
Street           0.041036
Alley            0.139868
LotShape        -0.255580
LandContour      0.015453
Utilities       -0.014314
LotConfig       -0.067396
LandSlope        0.051152
Neighborhood     0.210851
Condition1       0.091155
Condition2       0.007513
BldgType        -0.085591
HouseStyle       0.180163
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
RoofStyle        0.222405
RoofMatl         0.132383
Exterior1st      0.103551
Exterior2nd      0.103766
MasVnrType       0.018216
MasVnrArea       0.472614
ExterQual       -0.636884
ExterCond        0.117303
Foundation       0.382479
                   ...
SaleType        -0.054911
SaleCondition    0.213092
SalePrice        1.000000
FireplaceQu_0    0.255239
FireplaceQu_1   -0.026086
FireplaceQu_2    0.339329
FireplaceQu_3   -0.075916
FireplaceQu_4    0.163147
FireplaceQu_5   -0.471908
PoolQC_0         0.144146
PoolQC_1         0.016127
PoolQC_2         0.012038
PoolQC_3        -0.093708
MiscFeature_0   -0.004744
MiscFeature_1   -0.040538
MiscFeature_2   -0.069771
MiscFeature_3    0.022773
MiscFeature_4    0.072298
MoSold_1         0.005980
MoSold_2        -0.007355
MoSold_3         0.008219
MoSold_4        -0.038774
MoSold_5        -0.043714
MoSold_6        -0.020324
MoSold_7         0.029762
MoSold_8         0.014185
MoSold_9         0.039474
MoSold_10       -0.004354
MoSold_11        0.034001
MoSold_12        0.014465
Name: SalePrice, Length: 104, dtype: float64

In [995]:
def get_moderate_corrs(df, col_to_correlate):
    cols = df[df.columns].corr().columns
    corrs = df[df.columns].corr()[col_to_correlate]
    for col, corr in zip(cols, corrs):
        if abs(corr) < 0.01 and col != col_to_correlate:
            df = df.drop(columns=[col])
    return df

In [996]:
ids = df['Id']
df = get_moderate_corrs(df, 'SalePrice')
df['Id'] = ids

In [997]:
for column in df_test:
    if column not in df.columns:
        df_test = df_test.drop(columns=[column])

In [998]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature_3,MiscFeature_4,MoSold_4,MoSold_5,MoSold_6,MoSold_7,MoSold_8,MoSold_9,MoSold_11,MoSold_12
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,1,0,0,0,0,0,0,0,0
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,1,0,1,0,0,0,0,0,0
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,1,0,0,0,0,0,1,0,0
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,1,0,0,0,0,0,0,0,0
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,1,0,0,0,0,0,0,0,1

In [999]:
df.to_csv('clean_data.csv', index=False)
df_test.to_csv('clean_test.csv', index=False)